"""alters_likes_table

Revision ID: 5423b181a699
Revises: 9cda6d38f027
Create Date: 2020-12-29 15:02:22.283421

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5423b181a699'
down_revision = '9cda6d38f027'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key("likes_songs_id_fk", 'likes', 'songs', ['songId'], ['id'])
    op.create_foreign_key("likes_users_id_fk", 'likes', 'users', ['userId'], ['id'])
    op.drop_column('likes', 'id')
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint("likes_songs_id_fk", 'likes', type_='foreignkey')
    op.drop_constraint("likes_users_id_fk", 'likes', type_='foreignkey')
    # ### end Alembic commands ###
